language: python
dist: xenial
python: "3.5"
install: pip install cpplint

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - gcc-8
      - g++-8

script: export CC=gcc-8 && export CXX=g++-8 && make && make lint
